### ISSUE TITLE
Progress documentation on readme file?

### ISSUE THREAD

**Issue by johav** [FOSH-following-demand/Open-source-Centrifuge-for-WetLab#3]
| Week        | Products           | Call  | Status |
| ----------- | ------------------ | ----- |--------|
| Week 1      | GitHub repo + related_work.md + draft BoM          | 1st call with mentor  | Done
|             | Went to the lab and did usage research with scientist      |         |            |
| Week 2      | Order BoM + Dev Plan          | 2nd call with mentor  | Done |
|          | Designed and sent form based on Usage analysis                    |                 |      Done                |
| Week 3     | Updates on development          | 3rd call with mentor  | Done |
|            | Collecting Data and studying other models (of big and small centrifuges) |                |         |
|  |Development planned updated, Concept generation | Not able to build because of delayed delivery of components | |
| Week 4     | Got enough results to focus on two key issues: safety and cooling, as we haven't found an open hardware solution with cooling mechanism. Safety and balancing still can be improved in the commercial centrifuges we analyzed          | 4th called with mentor  | Done |
| Week 5  | Documenting new concepts and test cases, and updating ordering lists | 5th mentor called    |Done|

**Comment by jurra** [comment]
@johav thanks for the feedback. I am closing this issue, as we added the progress to our readme.
